image: maven:latest
variables:
  SONAR_TOKEN: "9cbed354721045a91fd778617ad4741c4f21bdd9"
  SONAR_HOST_URL: "http://jeffz.ngrok.io"
  GIT_DEPTH: 0
sonarqube-check:
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.security.sources.javasecurity.S2076=customSecurityConfig.json -Dsonar.security.sanitizers.javasecurity.S2076=customSecurityConfig.json -Dsonar.security.passthroughs.javasecurity.S2076=customSecurityConfig.json -Dsonar.security.sinks.javasecurity.S2076=customSecurityConfig.json
  allow_failure: false
  only:
    - merge_requests
    - master